# Generated by Django 4.1.5 on 2023-03-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=600),
        ),
    ]
