# Generated by Django 4.1.5 on 2023-03-25 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorrequest',
            name='date',
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutorme.course'),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=1200, null=True),
        ),
    ]
