# Generated by Django 4.1.5 on 2023-03-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0003_remove_tutorrequest_date_tutorrequest_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='description',
            field=models.TextField(blank=True, default='No description provided.', max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
