# Generated by Django 4.1.5 on 2023-03-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0004_alter_tutorrequest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='description',
            field=models.TextField(default='No description provided.', max_length=1200),
        ),
    ]
