# Generated by Django 4.1.5 on 2023-03-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0006_remove_tutorrequest_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=256),
        ),
    ]
